Description: Downloads the latest version and makes a pkg. Then, uploads the package to the Jamf Pro Server and creates a Self Service Policy and Smart Group.
Identifier: com.github.smithjw.jamf.Docker-Universal
ParentRecipe: com.github.smithjw.pkg.Docker-Universal
MinimumVersion: '2.3'

Input:
  NAME: Docker
  SOFTWARE_TITLE: '%NAME%'
  CATEGORY: Utilities
  GROUP_NAME: '%NAME%-update-smart'
  GROUP_TEMPLATE: SmartGroup-update-smart.xml
  TESTING_GROUP_NAME: Testing
  POLICY_CATEGORY: Testing
  POLICY_TEMPLATE: Policy-install-latest.xml
  POLICY_NAME: 'Install Latest %NAME% (%ARCHITECTURE%)'
  POLICY_RUN_COMMAND: ' '
  SELF_SERVICE_DISPLAY_NAME: 'Install Latest %NAME%'
  SELF_SERVICE_DESCRIPTION: 'Docker containers wrap a piece of software in a complete filesystem that contains everything needed to run: code, runtime, system tools, system libraries - anything that can be installed on a server. This guarantees that the software will always run the same, regardless of its environment.'
  SELF_SERVICE_ICON: '%NAME%.png'
  INSTALL_BUTTON_TEXT: 'Install'
  REINSTALL_BUTTON_TEXT: 'Install'
  UPDATE_PREDICATE: 'pkg_uploaded == False'

Process:
  - Processor: com.github.grahampugh.jamf-upload.processors/JamfCategoryUploader
    Arguments:
      category_name: '%CATEGORY%'

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfPackageUploader
    Arguments:
      pkg_category: '%CATEGORY%'

  - Processor: StopProcessingIf
    Arguments:
      predicate: '%UPDATE_PREDICATE%'

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerGroupUploader
    Arguments:
      computergroup_template: '%GROUP_TEMPLATE%'
      computergroup_name: '%GROUP_NAME%'

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfPolicyUploader
    Arguments:
      policy_template: '%POLICY_TEMPLATE%'
      policy_name: '%POLICY_NAME%'
      icon: '%SELF_SERVICE_ICON%'
